## Recitation 1 Test  (15 marks)

Make two 1D arrays 'u' and 'v' consisting of 3 uniform random numbers between 0 and 2 each. (**1 mark**)

In [4]:
import numpy as np
u = np.random.uniform(low=0, high=2, size=3) # generate integer random numbers between 0 and 2
print(u)
v = np.random.uniform(low=0, high=2, size=3) # generate integer random numbers between 0 and 2
print(v)

[0.03268858 0.73865628 0.25342509]
[0.43331658 0.82959851 1.40536431]


Compute the dot-product of 'u' and 'v'. (**1 mark**)

In [2]:
print("u⋅v =", np.dot(u, v))

u⋅v = 1.1751234170864135


Compute the lengths of vectors 'u' and 'v'. Vector lenghts are also called *magnitudes* or *norms*. (**1 mark**)

In [3]:
print("Magnitude of the vector u:",np.linalg.norm(u))
print("Magnitude of the vector v:",np.linalg.norm(v))

Magnitude of the vector u: 0.5582669462405487
Magnitude of the vector v: 2.1810111840324518


Find the angle between 'u' and 'v'. (**2 marks**)

In [8]:
import math
angle = np.dot(u, v)/(np.linalg.norm(u)*np.linalg.norm(v))
print("Cosθ =",angle)
angleInDegree = math.degrees(math.acos(angle))
print("θ =",angleInDegree,"°")

Cosθ = 0.9651252391808597
θ = 15.17621802690021 °


Compute the tensor-product of 'u' and 'v'. (**1 mark**)

In [9]:
print("A⨂B =\n", np.tensordot(u, v, axes=0))

A⨂B =
 [[0.17985002 0.3983537  0.1464595 ]
 [0.35292701 0.78170567 0.28740345]
 [0.26225788 0.58088066 0.21356773]]


Make a 2D array 'M' of size (2,3) containing uniform random numbers between 0 and 1. (**1 mark**)

In [13]:
M = np.random.uniform(low = 0,high = 1,size = (2,3))  # Create an array filled with random values
print(M) 

[[0.52416129 0.53051947 0.79849909]
 [0.1308489  0.40334615 0.88618984]]


Compute the matrix-vector product of 'M' and 'u'. (**1 mark**)

In [16]:
result = np.matmul(M,u.T)
print("u^T⋅v =\n", result)

u^T⋅v =
 [0.57690129 0.46805604]


Make an array 'A' consisting of a (3,4) array, a (2,4) array and a (4,4) array. All 3 arrays should contain random integers less than 9. (**1 mark**)

In [6]:
a1 = np.random.randint(9, size=(3,4))
a2 = np.random.randint(9, size=(2,4))
a3 = np.random.randint(9, size=(4,4))
A = np.array([a1, a2, a3])

print("A =\n", A.T)

A =
 [array([[6, 8, 4, 1],
       [7, 8, 4, 7],
       [0, 5, 3, 1]])
 array([[6, 0, 5, 0],
       [7, 4, 2, 6]])
 array([[1, 8, 8, 5],
       [0, 3, 0, 0],
       [8, 0, 3, 6],
       [1, 8, 2, 3]])]


Pad the three arrays in 'A' to make a tensor array 'B'. Padding should be at the top with constant value of -1. (**3 marks**)

In [8]:
pad_above1 = 4 - len(a1) # 4-3=1 len(a1) = 3x4
pad_above2 = 4 - len(a2) # 4-2=2 len(a2) = 2x4
pad_above3 = 4 - len(a3) # 4-4=0 len(a3) = 4x4
pad_below = 0
pad_left = 0
par_right = 0

n_add = [((pad_above1, pad_below), (pad_left, par_right)), # one tuple for each dimension
         ((pad_above2, pad_below), (pad_left, par_right)), 
         ((pad_above3, pad_below), (pad_left, par_right))]
print(n_add)
B = [np.pad(A[i], pad_width = n_add[i], mode = 'constant', constant_values = -1) for i in range(3)] # list comprehension returns list
B = np.array(B) # convert A3 into array again

print("A =\n", A)
print("B =\n", B)

[((1, 0), (0, 0)), ((2, 0), (0, 0)), ((0, 0), (0, 0))]
A =
 [array([[6, 8, 4, 1],
       [7, 8, 4, 7],
       [0, 5, 3, 1]])
 array([[6, 0, 5, 0],
       [7, 4, 2, 6]])
 array([[1, 8, 8, 5],
       [0, 3, 0, 0],
       [8, 0, 3, 6],
       [1, 8, 2, 3]])]
B =
 [[[-1 -1 -1 -1]
  [ 6  8  4  1]
  [ 7  8  4  7]
  [ 0  5  3  1]]

 [[-1 -1 -1 -1]
  [-1 -1 -1 -1]
  [ 6  0  5  0]
  [ 7  4  2  6]]

 [[ 1  8  8  5]
  [ 0  3  0  0]
  [ 8  0  3  6]
  [ 1  8  2  3]]]


Stack the arrays in 'A' vertically. (**1 mark**)

In [9]:
A1 = np.vstack(A) 
print(A1)

[[6 8 4 1]
 [7 8 4 7]
 [0 5 3 1]
 [6 0 5 0]
 [7 4 2 6]
 [1 8 8 5]
 [0 3 0 0]
 [8 0 3 6]
 [1 8 2 3]]


Stack the arrays in 'B' horizontally using only 1 line of code containing a for loop. (**2 marks**)

In [10]:
print([np.hstack(B[x])for x in range(3)])

[array([-1, -1, -1, -1,  6,  8,  4,  1,  7,  8,  4,  7,  0,  5,  3,  1]), array([-1, -1, -1, -1, -1, -1, -1, -1,  6,  0,  5,  0,  7,  4,  2,  6]), array([1, 8, 8, 5, 0, 3, 0, 0, 8, 0, 3, 6, 1, 8, 2, 3])]
