## Recitation1-Test2 (35 marks)

Create a matrix **A** of size (3,5) with 0 mean and 5 standard deviation. (**1 mark**)

In [2]:
import numpy as np
mu = 0
sigma = 5
A = np.random.normal(mu, sigma, size=(3,5)) # generate random numbers with mean 0.5 and sigma 1
print("A =\n", A)


A =
 [[  8.78835111  -7.89118135   3.96678511  -3.22722184  -0.93127369]
 [ -2.49498898   4.80488012   2.07047604   2.74894606 -15.59482637]
 [  8.6249263    6.76869453  -6.94491973   0.15243948  -9.19475022]]


Set all the elements in first row of **A** to 7. (**1 mark**)


In [3]:
A[0] = 7
print("A =\n", A)

A =
 [[  7.           7.           7.           7.           7.        ]
 [ -2.49498898   4.80488012   2.07047604   2.74894606 -15.59482637]
 [  8.6249263    6.76869453  -6.94491973   0.15243948  -9.19475022]]


Set all the elements in second row of **A** to -2. Set the element in third row and second column of **A** to 9. (**2 marks**) 

In [4]:
A[1] = -2
A.itemset((2, 1), 9)
print("A =\n", A)

A =
 [[ 7.          7.          7.          7.          7.        ]
 [-2.         -2.         -2.         -2.         -2.        ]
 [ 8.6249263   9.         -6.94491973  0.15243948 -9.19475022]]


Create a vector **a** of size 30 with values ranging from 60 to 89. (**2 marks**) 

In [5]:
int_rand_arr = np.random.randint(low=60, high=89, size=100) # generate integer random numbers between 1 and 100
print(int_rand_arr)

[71 78 83 82 67 70 68 63 70 77 76 71 84 84 81 69 79 87 77 85 68 64 64 79
 64 79 62 79 69 84 61 75 66 82 84 88 72 74 66 80 73 68 86 82 86 64 65 67
 68 74 83 88 81 63 72 85 81 65 76 65 78 62 72 69 71 77 61 84 60 85 82 83
 71 83 70 79 60 68 64 80 87 72 82 75 83 80 61 64 66 71 72 79 71 77 62 85
 82 83 77 83]


Create a (5,5) matrix **M** with values ranging from 0 to 24. (**1 mark**) 

In [8]:
M = np.random.randint(24, size=(5,5))
print("M =\n", M)

M =
 [[ 4  8 21 22 20]
 [ 5 12  6  0  1]
 [ 2 23 15 11 22]
 [20  6 22 11 20]
 [16 12 12 18  8]]


Make a (3,3) matrix **N** with 5 on the border and 0 inside. (**1 mark**) 

In [39]:
N = np.full((3,3), 5)
N.itemset((1, 1), 0)
print("N =\n", N)

N =
 [[5 5 5]
 [5 0 5]
 [5 5 5]]


Create a matrix **P** of size (3,4) with random integer values. (**1 mark**) 

In [9]:
P = np.random.randint(low=1, high=100, size=(3,4))  # Create an array filled with random values
print(P)                   

[[65 31 39 91]
 [55  6 99 24]
 [29 42 23 36]]


Subtract the mean of each row of matrix **A**. (**1 mark**) 

In [30]:
print(np.mean(A, axis=1))#did not understand the question

[ 7.         -2.          0.32753917]


**listA** =  [1,2,3,4,5,6,7,8,9,10]  

If an element of **listA** is smaller than 5, replace it with 0. And if an element of x is bigger than 5, replace it with 1. (**3 marks**) 

In [10]:
listA = [1,2,3,4,5,6,7,8,9,10]
listB = []
for x in listA:
    if(x < 5):
        listB.append(0)
    else:
        listB.append(1)
print(listB)

[0, 0, 0, 0, 1, 1, 1, 1, 1, 1]


Compute the square of **listA** elements in one line. (**2 marks**) 

In [11]:
squares = [x ** 2 for x in listA]
print(squares)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


Concatenate b1 and b2. (**2 marks**) 

In [20]:
b1 = np.array(['Hello', 'in','first'])
b2 = np.array(['Students','the','recitation'])
combine_b = ""
for i in range(3):
    combine_b += b1[i]
    combine_b += " "
    combine_b += b2[i]
    combine_b += " "
print(combine_b)    
    

Hello Students in the first recitation 


Split the element of combine_b (above list) with spaces. (**2 marks**) 

In [21]:
print(combine_b.split(" "))

['Hello', 'Students', 'in', 'the', 'first', 'recitation', '']


Create a 3-D array **L** with five on the diagonal and zeros elsewhere. (**1 mark**) 

In [23]:
L = np.zeros((3,3,3))
np.fill_diagonal(L, 5)
print(L)

[[[5. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 5. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 5.]]]


Make a function that can print a dictionary where the keys are numbers between 1 and 5 and the values are square of keys. (**2 marks**) 

In [26]:
my_dict = {1:1, 2:4, 3:9,4:16,5:25}
def print_dict(dict):
    for x, y in dict.items(): print("key and value:",x,y) 
print_dict(my_dict)

key and value: 1 1
key and value: 2 4
key and value: 3 9
key and value: 4 16
key and value: 5 25


Create a dictionary of student **Ali** where the keys are courses and values are total and obtaining marks in each course. Save this dictionary in a text file and numpy file. (**4 marks**) 

In [28]:
Ali = {"Deep Learning":(85,100), "MIA": (85,100), "AOAA": (85,100), "ACA": (85,100)}
print(Ali)
import pickle
pickle.dump(Ali, open("Ali1.txt", "wb"))
pickle.dump(Ali, open("Ali2.npy", "wb"))
loaded = pickle.load(open("Ali1.txt", "rb"))
loaded = pickle.load(open("Ali2.npy", "rb"))
print(loaded)

{'Deep Learning': (85, 100), 'MIA': (85, 100), 'AOAA': (85, 100), 'ACA': (85, 100)}
{'Deep Learning': (85, 100), 'MIA': (85, 100), 'AOAA': (85, 100), 'ACA': (85, 100)}


Create a class 'calculator' with the following functions to compute: **(9 marks)**
- the dot product between two vectors
- the cross product between two vectors
- the length (norm) of the vector
- matrix-vector product of **M** and **v**
- the mean squared error between **u**  and **v**
- the unit norm of vector **u**

In [53]:
M = np.array([[5,2,4],[2,9,8],[2,1,7]])
u = np.array([1,5,2])
v = np.array([4,2,3])
class Calculator:
    # Constructor
    def __init__(self): # Create an instance variable
        print("It is Constructor of my class")
    # Instance method    
    def dot_product(self,u,v):
        result = np.dot(u,v)
        print("Dot product of the vectors:",result)
    # Instance method    
    def cross_product(self,u,v):
        result = np.cross(u,v)
        print("Cross product of the vectors:",result)
    # Instance method    
    def magnitude(self,u):
        print("Magnitude of the vector:",np.linalg.norm(u))
    # Instance method    
    def matrix_vector_product(self,M,v):
        result = np.matmul(M,v.T)
        print("matrix_vector_product of the vectors:",result)
    # Instance method    
    def unit_norm(self,v):
        length = np.linalg.norm(v)
        print("unit norm of the vector:",v / length)
    # Instance method    
    def mean_squared_error(self,A,B):
        mse = (np.square(A - B)).mean()
        print("mean squared error between the vectors:",mse)
        
        
    
    


In [54]:
cal1 = Calculator() # Construct an instance of the person class
cal1.dot_product(u,v)
cal1.cross_product(u,v)
cal1.magnitude(M)
cal1.matrix_vector_product(M,v)
cal1.unit_norm(v)
cal1.mean_squared_error(u,v)

It is Constructor of my class
Dot product of the vectors: 20
Cross product of the vectors: [ 11   5 -18]
Magnitude of the vector: 15.748015748023622
matrix_vector_product of the vectors: [36 50 31]
unit norm of the vector: [0.74278135 0.37139068 0.55708601]
mean squared error between the vectors: 6.333333333333333
